### Stage 1
FROM node:alpine as build

RUN mkdir -p /home/app

WORKDIR /home/app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build 

### Stage 2
FROM nginx:alpine

ADD ./config/nginx-default.config /etc/nginx/conf.d/default.conf

COPY --from=build /home/app/dist /var/www/app/

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]