version: '3.9'
services:
  production:
    container_name: lista_productos
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:8080"
    volumes:
      - '.:/home/app/'
    env_file:
      - .env-prod
volumes:
  node_modules: