name: CI/CD

on:
  push:
    branches: [ "develop" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
      - uses: actions/checkout@v3

      - name: Build image
        run: docker compose -f docker-compose.prod.yml build
        
      - name: run image
        run: docker compose -f docker-compose.prod.yml push
  
