name: CI/CD

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: "0.0" # optional
          docker_compose: "docker-compose.prod.yml" # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
